name: persistence
description: A new Flutter package project.
version: 1.0.0-nullsafety
homepage: https://github.com/davidsdearaujo
git: https://github.com/davidsdearaujo/persistence

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  meta: ^1.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.7
  flutter_test:
    sdk: flutter

flutter:
