name: persistence
description: A new Flutter package project.
version: 1.0.0-nullsafety
author: David Araujo - Deivão
homepage: https://github.com/davidsdearaujo
git: https://github.com/davidsdearaujo/persistence

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  hive_flutter: ^0.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  meta: ^1.2.4
  mocktail: ^0.0.1-dev.7
  test: ^1.16.0-nullsafety.16
  
flutter: