name: persistence
description: A new Flutter package project.
version: 2.0.2
homepage: https://github.com/davidsdearaujo
git: https://github.com/davidsdearaujo/persistence

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  meta: ^1.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.7
  flutter_test:
    sdk: flutter

flutter:
