name: persistence
description: Package to help in a local persistence.
version: 1.0.0+1
homepage: https://github.com/davidsdearaujo/persistence
git: https://github.com/davidsdearaujo/persistence

environment:
  sdk: ">=2.7.0 <2.12.0-0"
  flutter: ">=1.17.0"

dependencies:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: